app:
  sleep-duration: 10s
  max-retries: 5
  currencies:
    - 980/UAH
    - 840/USD
    - 978/EUR
    - 756/CHF
    - 348/HUF
    - 826/GBP
    - 985/PLN
    - 8/ALL
    - 208/DKK

networks:
  mono/mp-rest/url: https://api.monobank.ua

quarkus:
  banner:
    path: banner.txt
  log:
    level: INFO
    console:
      enable: true
      json: false
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
      color: true
      darken: 0

"%dev":
  quarkus:
    log:
      min-level: TRACE
      console:
        darken: 1
      category:
        "com.yuriytkach":
          level: DEBUG

"%test":
  quarkus:
    log:
      min-level: TRACE
      category:
        "com.yuriytkach":
          level: TRACE
