version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  coverage-reporter: codacy/coverage-reporter@13.5.2

jobs:
  codacy-coverage-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dir
      - run: mkdir target; cp /tmp/dir/target/jacoco.exec target/jacoco.exec
      - coverage-reporter/send_report:
          skip: true
          project-token: ${CODACY_PROJECT_TOKEN}
          coverage-reports: target/site/jacoco/jacoco.xml

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: 
            name: maven/default
            tag: "11.0"
          post-steps:
            - persist_to_workspace:
                root: /tmp/dir
                paths:
                  - target/jacoco.exec
      - codacy-coverage-job:
          requires:
            - maven/test
