version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  coverage-reporter: codacy/coverage-reporter@13.5.2

jobs:
  codacy-coverage-job:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - coverage-reporter/send_report:
          project-token: ${CODACY_PROJECT_TOKEN}
          coverage-reports: build/reports/jacoco/jacocoTestReport.xml

workflows:
  gradle_test:
    jobs:
      - gradle/test:
          test_command: test quarkusIntTest
          post-steps:
            - persist_to_workspace:
                root: ~/
                paths:
                  - project/reports/jacoco/jacocoTestReport.xml
      - codacy-coverage-job:
          requires:
            - gradle/test
