name: Auto-update
# Auto-update only listens to `push` events.
# on: push
# If pull requests are always based on the same branches, only triggering the workflow when these branches receive new commits will minimize the workflow execution.
on:
  push:
    branches:
      - main

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-18.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: tibdex/auto-update@v2
        with:
          github_token: ${{ secrets.AUTOSQUASH_TOKEN }}
